# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hauptpunkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('sichtbar_ab', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['bezeichnung'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unterpunkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('sichtbar_ab', models.IntegerField(blank=True, default=0)),
                ('gehoert_zu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grundgeruest.Hauptpunkt')),
            ],
            options={
                'ordering': ['bezeichnung'],
                'abstract': False,
            },
        ),
    ]
