# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauptpunkt',
            name='nummer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unterpunkt',
            name='nummer',
            field=models.IntegerField(default=1),
        ),
    ]
