# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0002_auto_20170124_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hauptpunkt',
            options={'ordering': ['nummer']},
        ),
        migrations.AlterModelOptions(
            name='unterpunkt',
            options={'ordering': ['nummer']},
        ),
    ]
