# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20170124_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanzesMenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('gehoert_zu', models.ManyToManyField(to='Grundgeruest.Hauptpunkt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
