# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0002_auto_20170207_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='zu_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Medium'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='zu_veranstaltung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Veranstaltung'),
        ),
    ]
