# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0003_auto_20170207_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='preis',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
