# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0005_auto_20170212_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='preis',
        ),
    ]
