# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0006_remove_produkt_preis'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='preis',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
