# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0007_produkt_preis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name_plural': 'Produkte'},
        ),
        migrations.AddField(
            model_name='produkt',
            name='art_produkt',
            field=models.CharField(choices=[('Teilnahme', 'Teilnahme'), ('Livestream', 'Livestream'), ('Videoaufzeichnung', 'Videoaufzeichnung'), ('Audioaufzeichnung', 'Audioaufzeichnung')], default='', max_length=25),
        ),
    ]
