# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0001_initial'),
        ('Bibliothek', '0005_auto_20170224_0103'),
        ('Produkte', '0008_auto_20170212_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zu_buch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bibliothek.Buch'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='zu_buechlein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scholien.Buechlein'),
        ),
    ]
