# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170124_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholariumprofile',
            name='favourite_snack',
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='guthaben',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='stufe',
            field=models.IntegerField(choices=[(0, 'Interessent'), (1, 'Gast'), (2, 'Teilnehmer'), (3, 'Scholar'), (4, 'Partner'), (5, 'Beirat'), (6, 'Patron')], default=0),
        ),
    ]
