# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 12:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170125_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='plz',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
