# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0008_auto_20170212_1508'),
        ('accounts', '0006_auto_20170204_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kauf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nutzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ScholariumProfile')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produkte.Produkt')),
            ],
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='kaeufe',
            field=models.ManyToManyField(through='accounts.Kauf', to='Produkte.Produkt'),
        ),
    ]
