# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170220_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kauf',
            options={'verbose_name_plural': 'Käufe'},
        ),
        migrations.AddField(
            model_name='kauf',
            name='menge',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
