# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170221_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='kauf',
            name='guthaben_davor',
            field=models.SmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
