# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-25 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-datum_publizieren'], 'verbose_name_plural': 'Artikel'},
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='titel',
        ),
    ]
