# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artderveranstaltung',
            name='max_teilnehmer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artderveranstaltung',
            name='preis_aufzeichnung',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artderveranstaltung',
            name='preis_livestream',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='beschreibung',
            field=models.TextField(max_length=1200),
        ),
    ]
