# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0002_auto_20170125_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='artderveranstaltung',
            name='beschreibung',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='beschreibung',
            field=models.TextField(max_length=2000),
        ),
    ]
