# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0003_auto_20170125_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('link', models.SlugField(max_length=30)),
                ('datei', models.FileField(upload_to='')),
                ('typ', models.CharField(blank=True, max_length=30)),
                ('beschreibung', models.TextField(blank=True, max_length=2000, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='aufzeichnung',
        ),
        migrations.AddField(
            model_name='medium',
            name='gehoert_zu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veranstaltungen.Veranstaltung'),
        ),
    ]
