# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0004_auto_20170204_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='typ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
