# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-04 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0005_auto_20170204_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='link',
        ),
    ]
