# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0006_remove_medium_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artderveranstaltung',
            options={'verbose_name_plural': 'Arten der Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name_plural': 'Medien'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'verbose_name_plural': 'Veranstaltungen'},
        ),
    ]
