# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0007_auto_20170205_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='preis',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
