# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0008_medium_preis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='preis',
        ),
    ]
