# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('titel', models.CharField(blank=True, max_length=40, null=True)),
                ('autor', models.CharField(blank=True, max_length=40, null=True)),
                ('isbn', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('herausgeber', models.CharField(blank=True, max_length=40, null=True)),
                ('jahr', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
