# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buch',
            old_name='edition',
            new_name='ausgabe',
        ),
    ]
