# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0002_auto_20170222_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='notiz',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='serie',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='sprache',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='stichworte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
