# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0003_auto_20170222_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='exlibris',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
