# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0005_auto_20170224_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='zusammenfassung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
